version: '3.8'
services:
  nodejs:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: api_ejercicio_motos
    restart: always
    ports: 
      - 3000:3000
  angular:
    container_name: app-motos
    build: 
      context: ../app
      dockerfile: Dockerfile
    ports: 
      - "4200:4200"
    depends_on: 
      - nodejs