version: '3.8'
services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nginx-server2
    restart: always
    ports: 
      - 8080:80
    volumes:
      - ../app:/usr/share/nginx/html
volumes:
  app: {}